package Menus;

import java.awt.Color;

/**
 *
 * @author Fisher
 */
public class MenuDesplegable extends javax.swing.JFrame {

    /**
     * Creates new form BarraMenu
     */
    public MenuDesplegable() {
        initComponents();
        //Los grupos de botones los tenemos que manipular dentro del codigo
        grupoBotones.add(radio1);
        grupoBotones.add(radio2);
        grupoBotones.add(radio3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        menuDesplegable = new javax.swing.JPopupMenu();
        ventanaMaxima = new javax.swing.JMenuItem();
        ventanaMinima = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        cambiarColor = new javax.swing.JMenu();
        colorRojo = new javax.swing.JMenuItem();
        colorVerde = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemSalir = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        subMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        subMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        subMenu3 = new javax.swing.JMenu();
        radio1 = new javax.swing.JRadioButtonMenuItem();
        radio2 = new javax.swing.JRadioButtonMenuItem();
        radio3 = new javax.swing.JRadioButtonMenuItem();

        ventanaMaxima.setText("Ventana 500x500");
        ventanaMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaMaximaActionPerformed(evt);
            }
        });
        menuDesplegable.add(ventanaMaxima);

        ventanaMinima.setText("Ventana 100x100");
        ventanaMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaMinimaActionPerformed(evt);
            }
        });
        menuDesplegable.add(ventanaMinima);
        menuDesplegable.add(jSeparator3);

        cambiarColor.setText("Cambiar color de ventana");

        colorRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/colorrojo.png"))); // NOI18N
        colorRojo.setText("Color Rojo");
        colorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorRojoActionPerformed(evt);
            }
        });
        cambiarColor.add(colorRojo);

        colorVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/colorverde.png"))); // NOI18N
        colorVerde.setText("Color Verde");
        colorVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorVerdeActionPerformed(evt);
            }
        });
        cambiarColor.add(colorVerde);

        menuDesplegable.add(cambiarColor);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barra de menus");

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jMenu1.setText("Menú");

        jMenuItem1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenuItem1.setText("Inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        MenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/boton.png"))); // NOI18N
        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemSalir);
        jMenu1.add(jSeparator2);

        subMenu.setText("SubMenu");
        subMenu.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N

        jMenuItem2.setText("Item 1");
        subMenu.add(jMenuItem2);

        jMenuItem3.setText("Item 2");
        subMenu.add(jMenuItem3);

        jMenu1.add(subMenu);

        subMenu2.setText("Submenu CheckBox");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("item 1");
        subMenu2.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("item 2");
        subMenu2.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("item 3");
        subMenu2.add(jCheckBoxMenuItem3);

        jMenu1.add(subMenu2);

        subMenu3.setText("Submenu RadioButton");

        radio1.setSelected(true);
        radio1.setText("item 1");
        subMenu3.add(radio1);

        radio2.setSelected(true);
        radio2.setText("item 2");
        subMenu3.add(radio2);

        radio3.setSelected(true);
        radio3.setText("item 3");
        subMenu3.add(radio3);

        jMenu1.add(subMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        System.exit(0); //Cuando se presione SALIR, el programa se termina
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void panelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseReleased
        if (evt.isPopupTrigger()) { //Si se presiona click derecho, saldra el menu desplegable sobre el panel
            //Esto hara que cuando se presione click derecho, aparezca el Popup exactamente donde hicimos el click
            menuDesplegable.show(evt.getComponent(), evt.getX(), evt.getY()); //(En que componente debe aparecer, posicion X, posicion Y)
        }


    }//GEN-LAST:event_panelMouseReleased

    private void ventanaMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaMaximaActionPerformed
        this.setSize(500, 500); //Cuando se presiona el item, esta hara que la ventana sea mas grande
    }//GEN-LAST:event_ventanaMaximaActionPerformed

    private void ventanaMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaMinimaActionPerformed
        this.setSize(100, 100); //Cuando se presiona el item, esta hara que la ventana sea mas pequeña
    }//GEN-LAST:event_ventanaMinimaActionPerformed

    private void colorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorRojoActionPerformed
        panel.setBackground(Color.red);//Cuando se presiona el item, este hara el panel de color rojo
    }//GEN-LAST:event_colorRojoActionPerformed

    private void colorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorVerdeActionPerformed
        panel.setBackground(Color.GREEN);//Cuando se presiona el item, este hara el panel de color verde
    }//GEN-LAST:event_colorVerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDesplegable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDesplegable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDesplegable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDesplegable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDesplegable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JMenu cambiarColor;
    private javax.swing.JMenuItem colorRojo;
    private javax.swing.JMenuItem colorVerde;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu menuDesplegable;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButtonMenuItem radio1;
    private javax.swing.JRadioButtonMenuItem radio2;
    private javax.swing.JRadioButtonMenuItem radio3;
    private javax.swing.JMenu subMenu;
    private javax.swing.JMenu subMenu2;
    private javax.swing.JMenu subMenu3;
    private javax.swing.JMenuItem ventanaMaxima;
    private javax.swing.JMenuItem ventanaMinima;
    // End of variables declaration//GEN-END:variables
}
